# Generated by Django 4.1.6 on 2023-02-16 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WeldMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.TextField()),
                ('mass', models.IntegerField()),
                ('date_changed', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WeldMaterialUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('mass', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.weldmaterial')),
                ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('purchaser', models.CharField(default='Missing', max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_num', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('CA', 'Cancelled'), ('PS', 'Postponed'), ('HD', 'Hidden')], default='HD', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.post'),
        ),
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateField(default=django.utils.timezone.now)),
                ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.order')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(default=django.utils.timezone.now)),
                ('is_accepted_in', models.BooleanField()),
                ('date_out', models.DateField(default=django.utils.timezone.now)),
                ('is_accepted_out', models.BooleanField()),
                ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.order')),
            ],
        ),
    ]
