# Generated by Django 4.1.6 on 2023-02-14 05:34

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_order_weldmat_weldmatuse_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_accepted_in', models.BooleanField()),
                ('date_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_accepted_out', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubPost',
            fields=[
                ('post_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='blog.post')),
            ],
            bases=('blog.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='order_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(
                choices=[('AC', 'Active'), ('CA', 'Cancelled'), ('PS', 'Postponed'), ('HD', 'Hidden')], default='HD',
                max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Intake',
        ),
        migrations.AddField(
            model_name='subpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.post'),
        ),
        migrations.AddField(
            model_name='ingress',
            name='order_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.order'),
        ),
        migrations.AddField(
            model_name='control',
            name='order_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.order'),
        ),
    ]
