# Generated by Django 4.1.6 on 2023-02-19 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_chemicalcomposition_controlinput_controloutput_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveBigIntegerField()),
                ('deadline', models.DateField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='chemicalcomposition',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='controlinput',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='controloutput',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='ingress',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='penetranttesting',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='post',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='serial_num',
        ),
        migrations.RemoveField(
            model_name='weldmaterialuse',
            name='order_num',
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='Missing', max_length=100)),
                ('together', models.BooleanField(default=True)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='chemicalcomposition',
            name='serial_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.serialnumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlinput',
            name='serial_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.serialnumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controloutput',
            name='serial_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.serialnumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingress',
            name='serial_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.serialnumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penetranttesting',
            name='serial_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.serialnumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weldmaterialuse',
            name='serial_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.serialnumber'),
            preserve_default=False,
        ),
    ]
