# Generated by Django 4.1.6 on 2023-02-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_order_remove_chemicalcomposition_order_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.purchaser'),
        ),
    ]
