# Generated by Django 4.1.6 on 2023-02-14 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='order_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.order'),
        ),
    ]
