# Generated by Django 4.1.6 on 2023-02-19 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_purchaser_alter_post_purchaser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaserComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'LK1'), (2, 'LK2'), (3, 'LK3')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LaserHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Wobbler 200 mm'), (2, 'COAX'), (3, '4-side'), (4, 'Wobbler 500 mm'), (5, 'Nittany')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LaserWeldingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('mat_speed', models.PositiveSmallIntegerField()),
                ('welding_height', models.PositiveSmallIntegerField()),
                ('cladding_height', models.DecimalField(decimal_places=1, max_digits=2)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.lasercomplex')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.laserhead')),
            ],
        ),
        migrations.CreateModel(
            name='ShieldingGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Argon'), (2, 'K18')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.serialnumber')),
            ],
        ),
        migrations.AddField(
            model_name='weldmaterial',
            name='category',
            field=models.CharField(choices=[(1, 'Wire'), (2, 'Powder')], default='Wire', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TechCardOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.instrument')),
                ('laser_parameters', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.laserweldingparameters')),
                ('tc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.techcard')),
            ],
        ),
        migrations.AddField(
            model_name='laserweldingparameters',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.weldmaterial'),
        ),
        migrations.AddField(
            model_name='laserweldingparameters',
            name='shielding_gas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.shieldinggas'),
        ),
    ]
