# Generated by Django 4.1.6 on 2023-02-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_instrument_lasercomplex_laserhead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techcardoperations',
            name='laser_parameters',
        ),
    ]
