# Generated by Django 4.1.6 on 2023-02-14 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_alter_post_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
