# Generated by Django 4.1.6 on 2023-02-20 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_remove_techcardoperations_laser_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTaskSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shop', models.CharField(choices=[(1, 'Laser'), (2, 'Mechanical')], max_length=1)),
                ('shop_master', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[(1, 'LK1'), (2, 'LK2'), (3, 'LK3'), (4, 'Welding'), (5, 'Fitting'), (6, 'TS1620'), (7, 'FC'), (8, 'RT')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DayTaskSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.daytasksheet')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.site')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.techcard')),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.serialnumber')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.daytasksite')),
            ],
        ),
    ]
