# Generated by Django 4.1.6 on 2023-02-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_daytasksheet_site_daytasksite_daytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcard',
            name='laser_parameters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='blog.laserweldingparameters'),
            preserve_default=False,
        ),
    ]
