# Generated by Django 4.1.6 on 2023-02-14 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldmatuse',
            name='material',
        ),
        migrations.RemoveField(
            model_name='weldmatuse',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='weldmatuse',
            name='user',
        ),
        migrations.DeleteModel(
            name='WeldMat',
        ),
        migrations.DeleteModel(
            name='WeldMatUse',
        ),
    ]
