# Generated by Django 4.1.6 on 2023-02-20 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_techcard_laser_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytask',
            name='sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='blog.daytasksheet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daytask',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daytask',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.site'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='laser_parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.laserweldingparameters'),
        ),
        migrations.DeleteModel(
            name='DayTaskSite',
        ),
    ]
