# Generated by Django 4.1.6 on 2023-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_daytasksheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytasksheet',
            name='shop',
            field=models.IntegerField(choices=[(1, 'Laser'), (2, 'Mechanical')]),
        ),
    ]
