# Generated by Django 4.1.6 on 2023-02-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_daytasksheet_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='Worksite',
        ),
    ]
