# Generated by Django 4.1.6 on 2023-02-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_daytask_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcardoperations',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.instrument'),
        ),
    ]
