# Generated by Django 4.1.6 on 2023-02-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_daytask_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlinput',
            name='in_file',
            field=models.FileField(upload_to='ControlInput/'),
        ),
    ]
