# Generated by Django 4.1.6 on 2023-03-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_controlinput_in_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laserhead',
            name='name',
            field=models.CharField(choices=[(1, 'Wobbler 300 mm'), (2, 'COAX'), (3, '4-side'), (4, 'Wobbler 500 mm'), (5, 'Nittany')], max_length=1),
        ),
    ]
